add_newline = true
command_timeout = 1000

format = """$character"""
right_format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold green)"

[cmd_duration]
disabled = true

[golang]
format = """via [$symbol]($style)"""
symbol = " "

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "red"
